# **Tensors**

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters. Tensors are also optimized for automatic differentiation.

In [71]:
import torch
import numpy as np

## **Initializing a tensor**

In [72]:
# initialize a tensor
# 1. directly from data: the data type is inferred
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

# 2. from a numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

# 3. from another tensor
x_ones = torch.ones_like(x_data)  # retains the properties of x_data
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)  # overrides the datatype of x_data
print(x_rand)

# 4. using random or constant values
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")


tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 1],
        [1, 1]])
tensor([[0.5481, 0.6409],
        [0.7752, 0.6878]])
Random Tensor: 
 tensor([[0.2220, 0.7603, 0.5851],
        [0.4590, 0.1092, 0.3780]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## **Attributes of a tensor**

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [73]:
# create a tensor
tensor = torch.rand(3, 4)

shape = tensor.shape
datatype = tensor.dtype
device = tensor.device

print(f'Shape: {shape}, dtype: {datatype}, device: {device}')


Shape: torch.Size([3, 4]), dtype: torch.float32, device: cpu


## **Operations on Tensors**

Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing) sampling and more are comprehensively described here: https://pytorch.org/docs/stable/torch.html

Each of these operations can be run on the GPU (at typically higher speeds than on a CPU). By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability).

In [74]:
# create a Tensor
tensor = torch.ones(5, 4)
print(f'device (tensor): {tensor.device}')

# move to GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

print(f'device (tensor): {tensor.device}')

device (tensor): cpu
device (tensor): cuda:0


* **Standard numpy-like indexing and slicing**

In [75]:
print(f'First row: {tensor[0]}')
print(f'First column: {tensor[:, 0]}')
print(f'Last column: {tensor[..., -1]}')  # or tensor[:, -1]

# modify the second column
tensor[..., 1] = 0

# print
print(tensor)

First row: tensor([1., 1., 1., 1.], device='cuda:0')
First column: tensor([1., 1., 1., 1., 1.], device='cuda:0')
Last column: tensor([1., 1., 1., 1., 1.], device='cuda:0')
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='cuda:0')


* **Joining tensors**

You can use `torch.cat` to concatenate a sequence of tensors along a given dimension. See also `torch.stack`, another tensor joining operator that is subtly different from `torch.cat`.

In [76]:
t1 = torch.cat(tensors=[tensor, tensor], dim=0)
t1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='cuda:0')

* **Arithmetic ops**

In [77]:
# matrix multiplication
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

# element-wise product
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(z1)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='cuda:0')

* **Single-element tensors**

If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using `item()`:

In [78]:
agg = tensor.sum(dim=None)  # tensor(15., device='cuda:0')
agg_item = agg.item()
print(agg_item, type(agg_item))

15.0 <class 'float'>


* **In-place operations**

Operations that store the result into the operand are called in-place. They are denoted by a `_` suffix. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

In [79]:
print(f'{tensor}\n')
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='cuda:0')

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]], device='cuda:0')


* **Conversion ops: tensor to numpy array and vice-versa**

In [80]:
# create a tensor (1D)
t = torch.ones(5)
print(f't: {t}')

# convert to a numpy array
n = t.numpy()
print(f'n: {n}')

# a change in the tensor reflects in the numpy array
t.add_(1)
print(f't: {t}')
print(f'n: {n}')

# a change in the numpy array reflects in the tensor
np.add(n, 1, out=n)
print(f't: {t}')
print(f'n: {n}')

# convert numpy array to tensor
t1 = torch.from_numpy(n)
t1

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]
t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]


tensor([3., 3., 3., 3., 3.])